spring:
  application:
    name: api-gateway
server:
  port: 8082
zuul:
  routes:
    product-api:
      path: /api/**
      service-id: product-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
